apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricket-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cricket-app
  template:
    metadata:
      labels:
        app: cricket-app
    spec:
      containers:
      - name: cricket-app
        image: cricket-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
